import eventsData from "@/data/events.json";
import itemsData from "@/data/items.json";
import questGiversData from "@/data/questgivers.json";
import racesData from "@/data/races.json";
import type { BoardCard, BoardState, ItemRarity, Player, PlayerId, Zone, ZoneId } from "./types";

/** The 6 shared decks reshuffled by "New Game" — see Toolbar.tsx. */
export const STARTING_DECK_ZONE_IDS: ZoneId[] = [
	"event-deck",
	"item-deck-common",
	"item-deck-rare",
	"item-deck-magic",
	"quest-deck",
	"race-deck",
];

/**
 * Builds every real card from the Sheet-derived data files (src/data/*.json,
 * generated by `yarn data:sync`) plus the per-card art cropped by
 * `yarn data:art` — see AGENTS.md's Data Sources section. Items are sorted
 * into their rarity deck by `item.rarity`; events expand by their physical
 * `copies` count (one event is duplicated); quest givers and races each get
 * their own shared deck.
 */
function buildRealCards(): Record<string, BoardCard> {
	const cards: Record<string, BoardCard> = {};
	const orderByZone: Record<string, number> = {};

	function nextOrder(zoneId: string): number {
		const order = orderByZone[zoneId] ?? 0;
		orderByZone[zoneId] = order + 1;
		return order;
	}

	for (const item of itemsData) {
		const zoneId = `item-deck-${item.rarity}`;
		const id = `item-${item.id}`;
		const order = nextOrder(zoneId);
		cards[id] = {
			id,
			label: item.name,
			zoneId,
			position: { x: 0, y: 0 },
			order,
			sortOrder: order,
			faceDown: true,
			conditions: [],
			imageFront: item.imageFront,
			imageBack: item.imageBack,
			item: {
				itemType: item.itemType,
				rarity: item.rarity as ItemRarity,
				traits: item.traits,
				text: item.text,
				bonus: item.bonus,
				feature: item.feature,
				cost: item.cost,
			},
		};
	}

	for (const event of eventsData) {
		for (let copy = 0; copy < event.copies; copy++) {
			const id = `event-${event.id}-${copy}`;
			const order = nextOrder("event-deck");
			cards[id] = {
				id,
				label: event.name,
				zoneId: "event-deck",
				position: { x: 0, y: 0 },
				order,
				sortOrder: order,
				// Event cards are read aloud when drawn — the deck sits face-up
				// (unlike Items/Quests/Races, which stay hidden until drawn).
				faceDown: false,
				conditions: [],
				imageFront: event.imageFront,
				imageBack: event.imageBack,
			};
		}
	}

	for (const quest of questGiversData) {
		const id = `quest-${quest.id}`;
		const order = nextOrder("quest-deck");
		cards[id] = {
			id,
			label: quest.nickname,
			zoneId: "quest-deck",
			position: { x: 0, y: 0 },
			order,
			sortOrder: order,
			faceDown: true,
			conditions: [],
			imageFront: quest.imageFront,
			imageBack: quest.imageBack,
		};
	}

	for (const race of racesData) {
		const id = `race-${race.id}`;
		const order = nextOrder("race-deck");
		cards[id] = {
			id,
			label: race.nickname,
			zoneId: "race-deck",
			position: { x: 0, y: 0 },
			order,
			sortOrder: order,
			faceDown: true,
			conditions: [],
			imageFront: race.imageFront,
			imageBack: race.imageBack,
		};
	}

	return cards;
}

/**
 * Every zone a single player owns (Hand, Player Area, the 6 Equipped Items
 * slots) — factored out so the board scales to N players instead of one
 * hardcoded copy. Zone ids are namespaced by player id (e.g.
 * "player-2-hand"), so `zonesForPlayer("player-2")` never collides with
 * another player's zones.
 */
export function zonesForPlayer(playerId: PlayerId): Record<ZoneId, Zone> {
	const zones: Record<ZoneId, Zone> = {
		[`${playerId}-hand`]: {
			id: `${playerId}-hand`,
			kind: "hand",
			layout: "row",
			label: "Hand",
			ownerId: playerId,
		},
		[`${playerId}-area`]: {
			id: `${playerId}-area`,
			kind: "player-area",
			layout: "free",
			label: "Player Area",
			ownerId: playerId,
		},
		[`${playerId}-slot-head`]: {
			id: `${playerId}-slot-head`,
			kind: "player-area",
			layout: "slot",
			label: "Head",
			ownerId: playerId,
			icon: "/icon_head.svg",
		},
		[`${playerId}-slot-top`]: {
			id: `${playerId}-slot-top`,
			kind: "player-area",
			layout: "slot",
			label: "Top",
			ownerId: playerId,
			icon: "/icon_top.svg",
		},
		[`${playerId}-slot-legs`]: {
			id: `${playerId}-slot-legs`,
			kind: "player-area",
			layout: "slot",
			label: "Legs",
			ownerId: playerId,
			icon: "/icon_legs.svg",
		},
		[`${playerId}-slot-hand-main`]: {
			id: `${playerId}-slot-hand-main`,
			kind: "player-area",
			layout: "slot",
			label: "Hand",
			ownerId: playerId,
			icon: "/icon_hand.svg",
		},
		[`${playerId}-slot-hand-off`]: {
			id: `${playerId}-slot-hand-off`,
			kind: "player-area",
			layout: "slot",
			label: "Hand",
			ownerId: playerId,
			icon: "/icon_hand.svg",
		},
		[`${playerId}-slot-extra`]: {
			id: `${playerId}-slot-extra`,
			kind: "player-area",
			layout: "slot",
			label: "Extra",
			ownerId: playerId,
			icon: "/icon_extra.svg",
		},
	};
	return zones;
}

/** The 6 Equipped Items slot zone ids for a player, in display order. */
export function equippedSlotIds(playerId: PlayerId): ZoneId[] {
	return [
		`${playerId}-slot-head`,
		`${playerId}-slot-top`,
		`${playerId}-slot-legs`,
		`${playerId}-slot-hand-main`,
		`${playerId}-slot-hand-off`,
		`${playerId}-slot-extra`,
	];
}

/** Clamped to the 2-4 range offered on the homepage's local player picker. */
export function buildInitialState(requestedPlayerCount = 2, playerNames?: string[]): BoardState {
	const playerCount = Math.min(4, Math.max(2, requestedPlayerCount));
	const players: Player[] = Array.from({ length: playerCount }, (_, i) => ({
		id: `player-${i + 1}`,
		name: playerNames?.[i]?.trim() || `Player ${i + 1}`,
	}));

	const zones: Record<ZoneId, Zone> = {
		"event-deck": { id: "event-deck", kind: "deck", layout: "stack", label: "Event Deck" },
		"item-deck-common": {
			id: "item-deck-common",
			kind: "deck",
			layout: "stack",
			label: "Common Items",
		},
		"item-deck-rare": {
			id: "item-deck-rare",
			kind: "deck",
			layout: "stack",
			label: "Rare Items",
		},
		"item-deck-magic": {
			id: "item-deck-magic",
			kind: "deck",
			layout: "stack",
			label: "Magic Items",
		},
		"item-discard": {
			id: "item-discard",
			kind: "discard",
			layout: "stack",
			label: "Item Discard",
		},
		"quest-deck": { id: "quest-deck", kind: "deck", layout: "stack", label: "Quest Givers" },
		"race-deck": { id: "race-deck", kind: "deck", layout: "stack", label: "Races" },
	};

	for (const player of players) {
		Object.assign(zones, zonesForPlayer(player.id));
	}

	return {
		players,
		currentTurnPlayerId: players[0].id,
		round: 1,
		zones,
		cards: buildRealCards(),
		tokens: {},
	};
}
